spring:
  application:
    name: gulimall-third-part
  cloud:
    alicloud:
      access-key: LTAIqGC1FMgmXism
      secret-key: UYclIAmJwijF1GpBWEkEsJkC2XFHuM
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: ubuimgwarehouse
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 30000

